[aequnet]
enabled = true
chunk_size = 262144  # 256KB (Fibonacci-adjacent: 2^18)
max_content_size = 10485760  # 10MB for demo mode
dht_replication_factor = 5  # Fibonacci number - how many nodes store each content
content_ttl_days = 89  # Fibonacci - how long content is guaranteed to be available
prune_stale_nodes_seconds = 377  # Fibonacci - remove nodes not seen for this long

[aequnet.server]
host = "127.0.0.1"
port = 8000
max_connections = 233  # Fibonacci
enable_encryption = true
allowed_content_types = ["text/html", "text/css", "application/javascript", "image/png", "image/jpeg", "application/pdf"]

[aequnet.dht]
k_bucket_size = 8  # Fibonacci
alpha_parallelism = 3  # Fibonacci - parallel lookups
republish_interval_seconds = 987  # Fibonacci - how often to republish content locations
